restapiapp/urls.py
from django.urls import path
from .views import *


app_name = 'restapiapp'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path("clinician/create/api/", ClinicianApiCreateView.as_view(),
         name='clinicianapicreate'),
    path("clinician/<int:pk>/RUD/api/", ClinicianRUDView.as_view(),
         name='clinicianrudapi'),
    path("appointment/api/list-create/",
         AppointmentApiCreateView.as_view(), name='appointmentapicreate'),
    path("appointment/api/<int:pk>/RUD/",
         AppointmentApiRUDView.as_view(), name='appointmentrudapi'),
]

restapiproject/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restapiapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restapiapp/models.py
from django.db import models


class Clinician(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Appointment(models.Model):
    client_name = models.CharField(max_length=50)
    request_date = models.DateField()
    appointment_date = models.DateField()
    appointment_time = models.TimeField()
    preferred_clinician = models.ForeignKey(
        Clinician, on_delete=models.CASCADE)
    appointment_reason = models.TextField()

    def __str__(self):
        return self.client_name

restapiapp/views.py
from rest_framework.generics import (ListCreateAPIView,
                                     RetrieveUpdateDestroyAPIView)
from django.views.generic import TemplateView
from .serializers import *
from .models import *
from rest_framework.permissions import IsAdminUser


class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['appointmentlist'] = Appointment.objects.all(
        ).order_by('appointment_date')
        return context


class ClinicianApiCreateView(ListCreateAPIView):
    queryset = Clinician.objects.all()
    serializer_class = ClinicianSerializer


class ClinicianRUDView(RetrieveUpdateDestroyAPIView):
    queryset = Clinician.objects.all()
    serializer_class = ClinicianSerializer


class AppointmentApiCreateView(ListCreateAPIView):
    queryset = Appointment.objects.all()
    serializer_class = AppointmentSerializer
    # permission_classes = [IsAdminUser]


class AppointmentApiRUDView(RetrieveUpdateDestroyAPIView):
    queryset = Appointment.objects.all()
    serializer_class = AppointmentSerializer
    # permission_classes = [IsAdminUser]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body class="container">
	<a style="font-size: 18px;" href="{% url 'restapiapp:home' %}">Home</a> |
	<a style="font-size: 18px;" href="{% url 'restapiapp:clinicianapicreate' %}">Clinicial List-Create API</a> |
	<a style="font-size: 18px;" href="{% url 'restapiapp:appointmentapicreate' %}">APpList-Create API</a>
	<hr>
	{% block content %}


	{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}home{% endblock %}

{% block content %}
<h3 class="text-center text-info">Welcome to simple appointment management system</h3>
<div class="row">
	<div class="col-md-8">
		<h3>Appointment List</h3>
		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th>SN</th>
					<th>Client name</th>
					<th>Requested Date</th>
					<th>Appointment Date/Time</th>
					<th>Clinician </th>
					<th>RUD API</th>
				</tr>
			</thead>
			<tbody>
				{% for appointment in appointmentlist %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td>{{appointment.client_name}}</td>
					<td>{{appointment.request_date}}</td>
					<td>{{appointment.appointment_date}}{{appointment.appointment_date}}</td>
					<td>{{appointment.preferred_clinician.name}}</td>
					<td>
						<a href="{% url 'restapiapp:appointmentrudapi' appointment.id %}">View API</a>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	<div class="col-md-4">
		
	</div>
</div>
{% endblock %}